name: Trading Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Repository indir
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Kütüphaneleri kur
        run: pip install -r requirements.txt

      - name: Botu çalıştır
        run: python main.py
